ID_str = "ID"
AddedTime_str = "AddedTime"
FileSize_str = "FileSize"
Downloaded_str = "Downloaded"
Progress_str = "Progress"
URL_str = "URL"
Mirror_str = "Mirror"
FileName_str = "FileName"
FilePath_str = "FilePath"
Comment_str = "Comment"
User_str = "User"
Pass_str = "Pass"
Proxy_str = "Proxy"
PxPort_str = "PxPort"
MaxConn_str = "MaxConn"
ConnTimeout_str = "ConnTimeout"
MaxTry_str = "MaxTry"
TryDelay_str = "TryDelay"
DLSpeed_str = "DLSpeed"
TimeToFinish_str = "TimetoFinish"


JsonFileName = "downloads.json"

ID_Label = "ID"
FileName_Label = "File Name"
FileSize_Label = "File Size"
Progress_Label = "Progress"
DLSpeed_Label = "DL Speed"
TimeToFinish_Label = "Time to Finish"
